WITH CTE AS (
    SELECT


    TO_TIMESTAMP(STARTED_AT) as STARTED_AT,
    DATE(STARTED_AT) as DATE_STARTED_AT,
    HOUR(TRY_TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,

    CASE
    WHEN  DAYNAME(TO_TIMESTAMP(STARTED_AT)) IN ('Sat','Sun')
    THEN 'WEEKEND'
    ELSE 'BUSINESSDAY'
    END AS DAY_TYPE,

    CASE
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (12,1,2)
    THEN 'WINTER'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (3,4,5)
    THEN 'SPRING'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (6,7,8)
    THEN 'SUMMER'
    ELSE 'AUTUMN'
    END AS STATION_OF_YEAR

    FROM 
    {{ source('DEMO', 'BIKE') }}
    WHERE STARTED_AT != 'started_at'
)
SELECT
 * 
 FROM CTE